// Package resourcemodel code generated by /workspaces/terraform-provider-vyos/tools/build-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

import (
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// VrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddress describes the resource data model.
type VrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddress struct {
	// LeafNodes
	LeafVrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddressAsSet       types.String `tfsdk:"as_set" json:"as-set,omitempty"`
	LeafVrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddressRouteMap    types.String `tfsdk:"route_map" json:"route-map,omitempty"`
	LeafVrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddressSummaryOnly types.String `tfsdk:"summary_only" json:"summary-only,omitempty"`

	// TagNodes

	// Nodes
}

// ResourceSchemaAttributes generates the schema attributes for the resource at this level
func (o VrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddress) ResourceSchemaAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		// LeafNodes

		"as_set": schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Generate AS-set path information for this aggregate address

`,
		},

		"route_map": schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Specify route-map name to use

|  Format  |  Description  |
|----------|---------------|
|  txt  |  Route map name  |

`,
		},

		"summary_only": schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Announce the aggregate summary network only

`,
		},

		// TagNodes

		// Nodes

	}
}

// MarshalJSON returns json encoded string as bytes or error if marshalling did not go well
func (o *VrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddress) MarshalJSON() ([]byte, error) {
	jsonData := make(map[string]interface{})

	// Leafs

	if !o.LeafVrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddressAsSet.IsNull() && !o.LeafVrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddressAsSet.IsUnknown() {
		jsonData["as-set"] = o.LeafVrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddressAsSet.ValueString()
	}

	if !o.LeafVrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddressRouteMap.IsNull() && !o.LeafVrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddressRouteMap.IsUnknown() {
		jsonData["route-map"] = o.LeafVrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddressRouteMap.ValueString()
	}

	if !o.LeafVrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddressSummaryOnly.IsNull() && !o.LeafVrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddressSummaryOnly.IsUnknown() {
		jsonData["summary-only"] = o.LeafVrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddressSummaryOnly.ValueString()
	}

	// Tags

	// Nodes

	// Return compiled data
	ret, err := json.Marshal(jsonData)
	if err != nil {
		return nil, err
	}
	return ret, nil
}

// UnmarshalJSON unmarshals json byte array into this object
func (o *VrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddress) UnmarshalJSON(jsonStr []byte) error {
	jsonData := make(map[string]interface{})
	err := json.Unmarshal(jsonStr, &jsonData)
	if err != nil {
		return err
	}

	// Leafs

	if value, ok := jsonData["as-set"]; ok {
		o.LeafVrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddressAsSet = basetypes.NewStringValue(value.(string))
	} else {
		o.LeafVrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddressAsSet = basetypes.NewStringNull()
	}

	if value, ok := jsonData["route-map"]; ok {
		o.LeafVrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddressRouteMap = basetypes.NewStringValue(value.(string))
	} else {
		o.LeafVrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddressRouteMap = basetypes.NewStringNull()
	}

	if value, ok := jsonData["summary-only"]; ok {
		o.LeafVrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddressSummaryOnly = basetypes.NewStringValue(value.(string))
	} else {
		o.LeafVrfNameProtocolsBgpAddressFamilyIPvfourLabeledUnicastAggregateAddressSummaryOnly = basetypes.NewStringNull()
	}

	// Tags

	// Nodes

	return nil
}
