// Package resourcemodel code generated by /workspaces/terraform-provider-vyos/tools/build-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"

	"github.com/thomasfinstad/terraform-provider-vyos/internal/terraform/customtypes"
)

// QosPolicyNetworkEmulator describes the resource data model.
type QosPolicyNetworkEmulator struct {
	// LeafNodes
	QosPolicyNetworkEmulatorDescrIPtion customtypes.CustomStringValue `tfsdk:"description" json:"description,omitempty"`
	QosPolicyNetworkEmulatorBandwIDth   customtypes.CustomStringValue `tfsdk:"bandwidth" json:"bandwidth,omitempty"`
	QosPolicyNetworkEmulatorDelay       customtypes.CustomStringValue `tfsdk:"delay" json:"delay,omitempty"`
	QosPolicyNetworkEmulatorCorruption  customtypes.CustomStringValue `tfsdk:"corruption" json:"corruption,omitempty"`
	QosPolicyNetworkEmulatorDuplicate   customtypes.CustomStringValue `tfsdk:"duplicate" json:"duplicate,omitempty"`
	QosPolicyNetworkEmulatorLoss        customtypes.CustomStringValue `tfsdk:"loss" json:"loss,omitempty"`
	QosPolicyNetworkEmulatorReordering  customtypes.CustomStringValue `tfsdk:"reordering" json:"reordering,omitempty"`
	QosPolicyNetworkEmulatorQueueLimit  customtypes.CustomStringValue `tfsdk:"queue_limit" json:"queue-limit,omitempty"`

	// TagNodes

	// Nodes
}

// ResourceAttributes generates the attributes for the resource at this level
func (o QosPolicyNetworkEmulator) ResourceAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		// LeafNodes

		"description": schema.StringAttribute{
			CustomType: customtypes.CustomStringType{},
			Optional:   true,
			MarkdownDescription: `Description

|  Format  |  Description  |
|----------|---------------|
|  txt  |  Description  |
`,
		},

		"bandwidth": schema.StringAttribute{
			CustomType: customtypes.CustomStringType{},
			Optional:   true,
			MarkdownDescription: `Available bandwidth for this policy

|  Format  |  Description  |
|----------|---------------|
|  <number>  |  Bits per second  |
|  <number>bit  |  Bits per second  |
|  <number>kbit  |  Kilobits per second  |
|  <number>mbit  |  Megabits per second  |
|  <number>gbit  |  Gigabits per second  |
|  <number>tbit  |  Terabits per second  |
|  <number>%  |  Percentage of interface link speed  |
`,
		},

		"delay": schema.StringAttribute{
			CustomType: customtypes.CustomStringType{},
			Optional:   true,
			MarkdownDescription: `Adds delay to packets outgoing to chosen network interface

|  Format  |  Description  |
|----------|---------------|
|  <number>  |  Time in milliseconds  |
`,
		},

		"corruption": schema.StringAttribute{
			CustomType: customtypes.CustomStringType{},
			Optional:   true,
			MarkdownDescription: `Introducing error in a random position for chosen percent of packets

|  Format  |  Description  |
|----------|---------------|
|  <number>  |  Percentage of packets affected  |
`,
		},

		"duplicate": schema.StringAttribute{
			CustomType: customtypes.CustomStringType{},
			Optional:   true,
			MarkdownDescription: `Cosen percent of packets is duplicated before queuing them

|  Format  |  Description  |
|----------|---------------|
|  <number>  |  Percentage of packets affected  |
`,
		},

		"loss": schema.StringAttribute{
			CustomType: customtypes.CustomStringType{},
			Optional:   true,
			MarkdownDescription: `Add independent loss probability to the packets outgoing to chosen network interface

|  Format  |  Description  |
|----------|---------------|
|  <number>  |  Percentage of packets affected  |
`,
		},

		"reordering": schema.StringAttribute{
			CustomType: customtypes.CustomStringType{},
			Optional:   true,
			MarkdownDescription: `Emulated packet reordering percentage

|  Format  |  Description  |
|----------|---------------|
|  <number>  |  Percentage of packets affected  |
`,
		},

		"queue_limit": schema.StringAttribute{
			CustomType: customtypes.CustomStringType{},
			Optional:   true,
			MarkdownDescription: `Maximum queue size

|  Format  |  Description  |
|----------|---------------|
|  u32:1-4294967295  |  Queue size in packets  |
`,
		},

		// TagNodes

		// Nodes

	}
}
