/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl */
// Package namedvpnltwotpremoteaccessclientippool code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package namedvpnltwotpremoteaccessclientippool

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl */
import (
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/thomasfinstad/terraform-provider-vyos-rolling/internal/terraform/helpers"
)

/* tools/generate-terraform-resource-full/templates/resources/common/validate.gotmpl */
// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                = &vpnLtwotpRemoteAccessClientIPPool{}
	_ resource.ResourceWithConfigure   = &vpnLtwotpRemoteAccessClientIPPool{}
	_ resource.ResourceWithImportState = &vpnLtwotpRemoteAccessClientIPPool{}
)

// var _ resource.ResourceWithConfigValidators = &vpnLtwotpRemoteAccessClientIPPool{}
// var _ resource.ResourceWithModifyPlan = &vpnLtwotpRemoteAccessClientIPPool{}
// var _ resource.ResourceWithUpgradeState = &vpnLtwotpRemoteAccessClientIPPool{}
// var _ resource.ResourceWithValidateConfig = &vpnLtwotpRemoteAccessClientIPPool{}

// Ensure we fully satisfy helper pkg interfaces
var _ helpers.VyosResource = &vpnLtwotpRemoteAccessClientIPPool{}
