// Package globalfirewallglobaloptionsstatepolicyestablished code generated by /workspaces/terraform-provider-vyos/tools/build-terraform-resource-full/main.go. DO NOT EDIT.
package globalfirewallglobaloptionsstatepolicyestablished

import (
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource              = &firewallGlobalOptionsStatePolicyEstablished{}
	_ resource.ResourceWithConfigure = &firewallGlobalOptionsStatePolicyEstablished{}
)

// var _ resource.ResourceWithConfigValidators = &firewallGlobalOptionsStatePolicyEstablished{}
// var _ resource.ResourceWithModifyPlan = &firewallGlobalOptionsStatePolicyEstablished{}
// var _ resource.ResourceWithUpgradeState = &firewallGlobalOptionsStatePolicyEstablished{}
// var _ resource.ResourceWithValidateConfig = &firewallGlobalOptionsStatePolicyEstablished{}
// var _ resource.ResourceWithImportState = &firewallGlobalOptionsStatePolicyEstablished{}
