
terraform import vyos_service_dns_forwarding_authoritative_domain_records_naptr_rule.example "service__dns__forwarding__authoritative_domain__<authoritative-domain>__records__naptr__<naptr>__rule__<rule>"
