// Package namedvrfnameprotocolsospfinterfaceauthenticationmdfivekeyid code generated by /workspaces/terraform-provider-vyos/tools/build-terraform-resource-full/main.go. DO NOT EDIT.
package namedvrfnameprotocolsospfinterfaceauthenticationmdfivekeyid

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
)

// Metadata method to define the resource type name.
func (r vrfNameProtocolsOspfInterfaceAuthenticationMdfiveKeyID) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	r.ResourceName = req.ProviderTypeName + "_vrf_name_protocols_ospf_interface_authentication_md5_key_id"
	resp.TypeName = r.ResourceName
}
