
terraform import vyos_service_dns_forwarding_authoritative_domain_records_mx_server.example "service__dns__forwarding__authoritative_domain__<authoritative-domain>__records__mx__<mx>__server__<server>"
