default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: local
    hooks:
    -   id: no-autogen-on-dev-machines # Disabled for CI in .devcontainer/dockerfile-profile.d.sh
        name: No Autogen
        language: fail
        entry: |
          Only CI Workflow should commit files with "autogen" in their file path.
          Please use "git reset *autogen*" to un-stage the files.
        files: '.*autogen.*'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-yaml
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args:
        - --markdown-linebreak-ext=md
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: detect-private-key

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
  - repo: https://github.com/crate-ci/typos
    rev: v1.19.0
    hooks:
      - id: typos
        exclude: |
          (?x)^(
              data/provider-schema/.*\.json|
              .*/autogen.*|
              .*tmp
          )$
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-mod-tidy
      - id: go-fmt
  - repo: https://github.com/frnmst/md-toc
    rev: 9.0.0
    hooks:
      - id: md-toc
        args: ['-p', 'cmark', '-l6']
        exclude: |
          (?x)^(
            .*\.gotmpl|
            .*\.tmpl
          )$
