# Ref: https://github.com/crate-ci/typos/blob/master    /docs/reference.md
[default]
extend-ignore-re = [
    # Random data does not play well with a spell checker
    'api_key[=\s]+.*',

    # Misc
    "HashiCorp",
]
[files]
extend-exclude = [
    "*autogen*",
    "docs/*",
    "go.mod",
    "go.sum",
    "data/*",
    "examples/resources/*/import.sh",
]

[type.make]
extend-ignore-re = [
    # Command parameters can trigger spell check
    "make.*",
]

[type.tf]
extend-ignore-re = [
    # Dummy interface wants to be "dumb"
    "dum",
]
