
terraform import vyos_interfaces_ethernet_vif_s_vif_c_dhcpv6_options_pd_interface.example "interfaces__ethernet__<ethernet>__vif_s__<vif-s>__vif_c__<vif-c>__dhcpv6_options__pd__<pd>__interface__<interface>"
