
terraform import vyos_service_dhcpv6_server_shared_network_name_subnet_static_mapping.example "service__dhcpv6_server__shared_network_name__<shared-network-name>__subnet__<subnet>__static_mapping__<static-mapping>"
