// Package namedprotocolsstatictableroutesixnexthop code generated by /workspaces/terraform-provider-vyos/tools/build-terraform-resource-full/main.go. DO NOT EDIT.
package namedprotocolsstatictableroutesixnexthop

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

// Schema method to define the schema for any resource configuration, plan, and state data.
func (r protocolsStaticTableRoutesixNextHop) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: `<div style="text-align: center">
Routing protocols

<br>
&darr;
<br>
Static Routing

<br>
&darr;
<br>
Policy route table number

<br>
&darr;
<br>
Static IPv6 route

<br>
&darr;
<br>
<b>
IPv6 gateway address
</b>
</div>
`,
		Attributes: r.model.ResourceSchemaAttributes(),
	}
}
