
terraform import vyos_interfaces_virtual_ethernet_vif_dhcpv6_options_pd_interface.example "interfaces__virtual-ethernet__<virtual-ethernet>__vif__<vif>__dhcpv6-options__pd__<pd>__interface__<interface>"
