// Package resourcemodel code generated by /workspaces/terraform-provider-vyos/tools/build-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// ProtocolsBfdProfile describes the resource data model.
type ProtocolsBfdProfile struct {
	ID types.String `tfsdk:"identifier" vyos:",self-id"`

	// LeafNodes
	LeafProtocolsBfdProfileEchoMode types.Bool `tfsdk:"echo_mode" vyos:"echo-mode,omitempty"`
	LeafProtocolsBfdProfilePassive  types.Bool `tfsdk:"passive" vyos:"passive,omitempty"`
	LeafProtocolsBfdProfileShutdown types.Bool `tfsdk:"shutdown" vyos:"shutdown,omitempty"`

	// TagNodes (Bools that show if child resources have been configured)

	// Nodes
	NodeProtocolsBfdProfileInterval *ProtocolsBfdProfileInterval `tfsdk:"interval" vyos:"interval,omitempty"`
}

// GetVyosPath returns the list of strings to use to get to the correct vyos configuration
func (o *ProtocolsBfdProfile) GetVyosPath() []string {
	return []string{
		"protocols",

		"bfd",

		"profile",
		o.ID.ValueString(),
	}
}

// ResourceSchemaAttributes generates the schema attributes for the resource at this level
func (o ProtocolsBfdProfile) ResourceSchemaAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"identifier": schema.StringAttribute{
			Required: true,
			MarkdownDescription: `Configure BFD profile used by individual peer

    |  Format  |  Description  |
    |----------|---------------|
    |  txt  |  Name of BFD profile  |

`,
		},

		// LeafNodes

		"echo_mode": schema.BoolAttribute{
			Optional: true,
			MarkdownDescription: `Enables the echo transmission mode

`,
			Default:  booldefault.StaticBool(false),
			Computed: true,
		},

		"passive": schema.BoolAttribute{
			Optional: true,
			MarkdownDescription: `Do not attempt to start sessions

`,
			Default:  booldefault.StaticBool(false),
			Computed: true,
		},

		"shutdown": schema.BoolAttribute{
			Optional: true,
			MarkdownDescription: `Disable this peer

`,
			Default:  booldefault.StaticBool(false),
			Computed: true,
		},

		// Nodes

		"interval": schema.SingleNestedAttribute{
			Attributes: ProtocolsBfdProfileInterval{}.ResourceSchemaAttributes(),
			Optional:   true,
			MarkdownDescription: `Configure timer intervals

`,
		},
	}
}

// MarshalJSON returns json encoded string as bytes or error if marshalling did not go well
func (o *ProtocolsBfdProfile) MarshalJSON() ([]byte, error) {
	return nil, nil
}

// UnmarshalJSON unmarshals json byte array into this object
func (o *ProtocolsBfdProfile) UnmarshalJSON(_ []byte) error {
	return nil
}
