// Package namedservicentpptptimestampinterface code generated by tools/build-terraform-resource-full/main.go. DO NOT EDIT.
package namedservicentpptptimestampinterface

import (
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/thomasfinstad/terraform-provider-vyos-rolling/internal/terraform/helpers"
)

// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource              = &serviceNtpPtpTimestampInterface{}
	_ resource.ResourceWithConfigure = &serviceNtpPtpTimestampInterface{}
)

// var _ resource.ResourceWithConfigValidators = &serviceNtpPtpTimestampInterface{}
// var _ resource.ResourceWithModifyPlan = &serviceNtpPtpTimestampInterface{}
// var _ resource.ResourceWithUpgradeState = &serviceNtpPtpTimestampInterface{}
// var _ resource.ResourceWithValidateConfig = &serviceNtpPtpTimestampInterface{}
// var _ resource.ResourceWithImportState = &serviceNtpPtpTimestampInterface{}

// Ensure we fully satisfy helper pkg interfaces
var _ helpers.VyosResource = &serviceNtpPtpTimestampInterface{}
