
terraform import vyos_interfaces_virtual_ethernet_vif_s_dhcpv6_options_pd_interface.example "interfaces__virtual_ethernet__<virtual-ethernet>__vif_s__<vif-s>__dhcpv6_options__pd__<pd>__interface__<interface>"
