// Package globalservicentp code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package globalservicentp

import (
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/thomasfinstad/terraform-provider-vyos-rolling/internal/terraform/helpers"
)

// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource              = &serviceNtp{}
	_ resource.ResourceWithConfigure = &serviceNtp{}
)

// var _ resource.ResourceWithConfigValidators = &serviceNtp{}
// var _ resource.ResourceWithModifyPlan = &serviceNtp{}
// var _ resource.ResourceWithUpgradeState = &serviceNtp{}
// var _ resource.ResourceWithValidateConfig = &serviceNtp{}
// var _ resource.ResourceWithImportState = &serviceNtp{}

// Ensure we fully satisfy helper pkg interfaces
var _ helpers.VyosResource = &serviceNtp{}
