
terraform import vyos_service_dhcp_server_shared_network_name_subnet_static_mapping.example "service__dhcp-server__shared-network-name__<shared-network-name>__subnet__<subnet>__static-mapping__<static-mapping>"
