
terraform import vyos_service_dhcp_server_shared_network_name_subnet_static_mapping.example "service__dhcp_server__shared_network_name__<shared-network-name>__subnet__<subnet>__static_mapping__<static-mapping>"
