
terraform import vyos_protocols_isis_fast_reroute_lfa_local_tiebreaker_lowest_backup_metric_index.example "protocols__isis__fast_reroute__lfa__local__tiebreaker__lowest_backup_metric__index__<index>"
