// Package resourcemodel code generated by /workspaces/terraform-provider-vyos/tools/build-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// ProtocolsBabelDistributeListIPvfourInterface describes the resource data model.
type ProtocolsBabelDistributeListIPvfourInterface struct {
	// LeafNodes

	// TagNodes

	// Nodes
	ProtocolsBabelDistributeListIPvfourInterfaceAccessList types.Object `tfsdk:"access_list" json:"access-list,omitempty"`
	ProtocolsBabelDistributeListIPvfourInterfacePrefixList types.Object `tfsdk:"prefix_list" json:"prefix-list,omitempty"`
}

// ResourceAttributes generates the attributes for the resource at this level
func (o ProtocolsBabelDistributeListIPvfourInterface) ResourceAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		// LeafNodes

		// TagNodes

		// Nodes

		"access_list": schema.SingleNestedAttribute{
			Attributes: ProtocolsBabelDistributeListIPvfourInterfaceAccessList{}.ResourceAttributes(),
			Optional:   true,
			MarkdownDescription: `Access-list

`,
		},

		"prefix_list": schema.SingleNestedAttribute{
			Attributes: ProtocolsBabelDistributeListIPvfourInterfacePrefixList{}.ResourceAttributes(),
			Optional:   true,
			MarkdownDescription: `Prefix-list

`,
		},
	}
}
