
terraform import vyos_vrf_name_protocols_ospf_area_virtual_link_authentication_md5_key_id.example "vrf__name__<name>__protocols__ospf__area__<area>__virtual-link__<virtual-link>__authentication__md5__key-id__<key-id>"
