
terraform import vyos_vrf_name_protocols_bgp_address_family_ipv6_unicast_aggregate_address.example "vrf__name__<name>__protocols__bgp__address-family__ipv6-unicast__aggregate-address__<aggregate-address>"
