// Package resourcemodel code generated by /workspaces/terraform-provider-vyos/tools/build-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"

	"github.com/thomasfinstad/terraform-provider-vyos/internal/terraform/customtypes"
)

// ServiceIPoeServerAuthenticationInterfaceMacRateLimit describes the resource data model.
type ServiceIPoeServerAuthenticationInterfaceMacRateLimit struct {
	// LeafNodes
	ServiceIPoeServerAuthenticationInterfaceMacRateLimitUpload   customtypes.CustomStringValue `tfsdk:"upload" json:"upload,omitempty"`
	ServiceIPoeServerAuthenticationInterfaceMacRateLimitDownload customtypes.CustomStringValue `tfsdk:"download" json:"download,omitempty"`

	// TagNodes

	// Nodes
}

// ResourceAttributes generates the attributes for the resource at this level
func (o ServiceIPoeServerAuthenticationInterfaceMacRateLimit) ResourceAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		// LeafNodes

		"upload": schema.StringAttribute{
			CustomType: customtypes.CustomStringType{},
			Optional:   true,
			MarkdownDescription: `Upload bandwidth limit in kbits/sec

`,
		},

		"download": schema.StringAttribute{
			CustomType: customtypes.CustomStringType{},
			Optional:   true,
			MarkdownDescription: `Download bandwidth limit in kbits/sec

`,
		},

		// TagNodes

		// Nodes

	}
}
