/* tools/generate-terraform-resource-full/templates/resources/common/package.gotmpl #package (<no value>) */
// Package resourcemodel code generated by tools/generate-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

/* tools/generate-terraform-resource-full/templates/resources/common/imports.gotmpl #imports (.) */
import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/thomasfinstad/terraform-provider-vyos-rolling/internal/terraform/helpers"
)

/* tools/generate-terraform-resource-full/templates/resources/common/resource-model.gotmpl #resource-model (multi-hop) */
// Validate compliance

var _ helpers.VyosResourceDataModel = &ProtocolsStaticRouteNextHopBfdMultiHop{}

// ProtocolsStaticRouteNextHopBfdMultiHop describes the resource data model.
// This is not a basenode!
// Top level basenode type: `N/A`
type ProtocolsStaticRouteNextHopBfdMultiHop struct {
	// LeafNodes
	LeafProtocolsStaticRouteNextHopBfdMultiHopSourceAddress types.String `tfsdk:"source_address" vyos:"source-address,omitempty"`

	// TagNodes

	// Nodes
}

// ResourceSchemaAttributes generates the schema attributes for the resource at this level
func (o ProtocolsStaticRouteNextHopBfdMultiHop) ResourceSchemaAttributes(ctx context.Context) map[string]schema.Attribute {
	return map[string]schema.Attribute{
		// LeafNodes

		"source_address":

		/* tools/generate-terraform-resource-full/templates/resources/common/resource-model-schema-attrtype.gotmpl #resource-model-schema-attrtype (source-address) */
		schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `IPv4 address used to initiate connection

    |  Format  |  Description          |
    |----------|-----------------------|
    |  ipv4    |  IPv4 source address  |
`,
			Description: `IPv4 address used to initiate connection

    |  Format  |  Description          |
    |----------|-----------------------|
    |  ipv4    |  IPv4 source address  |
`,
		},

		// TagNodes

		// Nodes

	}
}
