// Package resourcemodel code generated by /workspaces/terraform-provider-vyos/tools/build-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// PolicyRouteRuleLimit describes the resource data model.
type PolicyRouteRuleLimit struct {
	// LeafNodes
	LeafPolicyRouteRuleLimitBurst types.Number `tfsdk:"burst" vyos:"burst,omitempty"`
	LeafPolicyRouteRuleLimitRate  types.Number `tfsdk:"rate" vyos:"rate,omitempty"`

	// TagNodes (Bools that show if child resources have been configured)

	// Nodes
}

// ResourceSchemaAttributes generates the schema attributes for the resource at this level
func (o PolicyRouteRuleLimit) ResourceSchemaAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		// LeafNodes

		"burst": schema.NumberAttribute{
			Optional: true,
			MarkdownDescription: `Maximum number of packets to allow in excess of rate

    |  Format  |  Description  |
    |----------|---------------|
    |  u32:0-4294967295  |  Maximum number of packets to allow in excess of rate  |

`,
		},

		"rate": schema.NumberAttribute{
			Optional: true,
			MarkdownDescription: `Maximum average matching rate

    |  Format  |  Description  |
    |----------|---------------|
    |  u32:0-4294967295  |  Maximum average matching rate  |

`,
		},

		// Nodes

	}
}

// MarshalJSON returns json encoded string as bytes or error if marshalling did not go well
func (o *PolicyRouteRuleLimit) MarshalJSON() ([]byte, error) {
	return nil, nil
}

// UnmarshalJSON unmarshals json byte array into this object
func (o *PolicyRouteRuleLimit) UnmarshalJSON(_ []byte) error {
	return nil
}
