// Package resourcemodel code generated by /workspaces/terraform-provider-vyos/tools/build-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// NatDestinationRuleDestinationGroup describes the resource data model.
type NatDestinationRuleDestinationGroup struct {
	// LeafNodes
	LeafNatDestinationRuleDestinationGroupAddressGroup types.String `tfsdk:"address_group"`
	LeafNatDestinationRuleDestinationGroupDomainGroup  types.String `tfsdk:"domain_group"`
	LeafNatDestinationRuleDestinationGroupMacGroup     types.String `tfsdk:"mac_group"`
	LeafNatDestinationRuleDestinationGroupNetworkGroup types.String `tfsdk:"network_group"`
	LeafNatDestinationRuleDestinationGroupPortGroup    types.String `tfsdk:"port_group"`

	// TagNodes

	// Nodes
}

// TerraformToVyos converts terraform data to vyos data
func (o *NatDestinationRuleDestinationGroup) TerraformToVyos(ctx context.Context, diags *diag.Diagnostics) map[string]interface{} {
	tflog.Error(ctx, "TerraformToVyos", map[string]interface{}{"Path": []string{"nat", "destination", "rule", "destination", "group"}})

	vyosData := make(map[string]interface{})

	// Leafs
	if !(o.LeafNatDestinationRuleDestinationGroupAddressGroup.IsNull() || o.LeafNatDestinationRuleDestinationGroupAddressGroup.IsUnknown()) {
		vyosData["address-group"] = o.LeafNatDestinationRuleDestinationGroupAddressGroup.ValueString()
	}
	if !(o.LeafNatDestinationRuleDestinationGroupDomainGroup.IsNull() || o.LeafNatDestinationRuleDestinationGroupDomainGroup.IsUnknown()) {
		vyosData["domain-group"] = o.LeafNatDestinationRuleDestinationGroupDomainGroup.ValueString()
	}
	if !(o.LeafNatDestinationRuleDestinationGroupMacGroup.IsNull() || o.LeafNatDestinationRuleDestinationGroupMacGroup.IsUnknown()) {
		vyosData["mac-group"] = o.LeafNatDestinationRuleDestinationGroupMacGroup.ValueString()
	}
	if !(o.LeafNatDestinationRuleDestinationGroupNetworkGroup.IsNull() || o.LeafNatDestinationRuleDestinationGroupNetworkGroup.IsUnknown()) {
		vyosData["network-group"] = o.LeafNatDestinationRuleDestinationGroupNetworkGroup.ValueString()
	}
	if !(o.LeafNatDestinationRuleDestinationGroupPortGroup.IsNull() || o.LeafNatDestinationRuleDestinationGroupPortGroup.IsUnknown()) {
		vyosData["port-group"] = o.LeafNatDestinationRuleDestinationGroupPortGroup.ValueString()
	}

	// Tags

	// Nodes

	// Return compiled data
	return vyosData
}

// VyosToTerraform converts vyos data to terraform data
func (o *NatDestinationRuleDestinationGroup) VyosToTerraform(ctx context.Context, diags *diag.Diagnostics, vyosData map[string]interface{}) {
	tflog.Error(ctx, "VyosToTerraform begin", map[string]interface{}{"Path": []string{"nat", "destination", "rule", "destination", "group"}})

	// Leafs
	if value, ok := vyosData["address-group"]; ok {
		o.LeafNatDestinationRuleDestinationGroupAddressGroup = basetypes.NewStringValue(value.(string))
	} else {
		o.LeafNatDestinationRuleDestinationGroupAddressGroup = basetypes.NewStringNull()
	}
	if value, ok := vyosData["domain-group"]; ok {
		o.LeafNatDestinationRuleDestinationGroupDomainGroup = basetypes.NewStringValue(value.(string))
	} else {
		o.LeafNatDestinationRuleDestinationGroupDomainGroup = basetypes.NewStringNull()
	}
	if value, ok := vyosData["mac-group"]; ok {
		o.LeafNatDestinationRuleDestinationGroupMacGroup = basetypes.NewStringValue(value.(string))
	} else {
		o.LeafNatDestinationRuleDestinationGroupMacGroup = basetypes.NewStringNull()
	}
	if value, ok := vyosData["network-group"]; ok {
		o.LeafNatDestinationRuleDestinationGroupNetworkGroup = basetypes.NewStringValue(value.(string))
	} else {
		o.LeafNatDestinationRuleDestinationGroupNetworkGroup = basetypes.NewStringNull()
	}
	if value, ok := vyosData["port-group"]; ok {
		o.LeafNatDestinationRuleDestinationGroupPortGroup = basetypes.NewStringValue(value.(string))
	} else {
		o.LeafNatDestinationRuleDestinationGroupPortGroup = basetypes.NewStringNull()
	}

	// Tags

	// Nodes

	tflog.Error(ctx, "VyosToTerraform end", map[string]interface{}{"Path": []string{"nat", "destination", "rule", "destination", "group"}})
}

// AttributeTypes generates the attribute types for the resource at this level
func (o NatDestinationRuleDestinationGroup) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		// Leafs
		"address_group": types.StringType,
		"domain_group":  types.StringType,
		"mac_group":     types.StringType,
		"network_group": types.StringType,
		"port_group":    types.StringType,

		// Tags

		// Nodes

	}
}

// ResourceSchemaAttributes generates the schema attributes for the resource at this level
func (o NatDestinationRuleDestinationGroup) ResourceSchemaAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		// LeafNodes

		"address_group": schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Group of addresses

`,
		},

		"domain_group": schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Group of domains

`,
		},

		"mac_group": schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Group of MAC addresses

`,
		},

		"network_group": schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Group of networks

`,
		},

		"port_group": schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Group of ports

`,
		},

		// TagNodes

		// Nodes

	}
}
