// Package resourcemodel code generated by /workspaces/terraform-provider-vyos/tools/build-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

import (
	"encoding/json"
	"reflect"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// NatDestinationRuleTranSLAtion describes the resource data model.
type NatDestinationRuleTranSLAtion struct {
	// LeafNodes
	LeafNatDestinationRuleTranSLAtionAddress types.String `tfsdk:"address" json:"address,omitempty"`
	LeafNatDestinationRuleTranSLAtionPort    types.String `tfsdk:"port" json:"port,omitempty"`

	// TagNodes

	// Nodes
	NodeNatDestinationRuleTranSLAtionOptions *NatDestinationRuleTranSLAtionOptions `tfsdk:"options" json:"options,omitempty"`
}

// ResourceSchemaAttributes generates the schema attributes for the resource at this level
func (o NatDestinationRuleTranSLAtion) ResourceSchemaAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		// LeafNodes

		"address": schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `IP address, subnet, or range

|  Format  |  Description  |
|----------|---------------|
|  ipv4  |  IPv4 address to match  |
|  ipv4net  |  IPv4 prefix to match  |
|  ipv4range  |  IPv4 address range to match  |

`,
		},

		"port": schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Port number

|  Format  |  Description  |
|----------|---------------|
|  u32:1-65535  |  Numeric IP port  |
|  range  |  Numbered port range (e.g., 1001-1005)  |

`,
		},

		// TagNodes

		// Nodes

		"options": schema.SingleNestedAttribute{
			Attributes: NatDestinationRuleTranSLAtionOptions{}.ResourceSchemaAttributes(),
			Optional:   true,
			MarkdownDescription: `Translation options

`,
		},
	}
}

// MarshalJSON returns json encoded string as bytes or error if marshalling did not go well
func (o *NatDestinationRuleTranSLAtion) MarshalJSON() ([]byte, error) {
	jsonData := make(map[string]interface{})

	// Leafs

	if !o.LeafNatDestinationRuleTranSLAtionAddress.IsNull() && !o.LeafNatDestinationRuleTranSLAtionAddress.IsUnknown() {
		jsonData["address"] = o.LeafNatDestinationRuleTranSLAtionAddress.ValueString()
	}

	if !o.LeafNatDestinationRuleTranSLAtionPort.IsNull() && !o.LeafNatDestinationRuleTranSLAtionPort.IsUnknown() {
		jsonData["port"] = o.LeafNatDestinationRuleTranSLAtionPort.ValueString()
	}

	// Tags

	// Nodes

	if !reflect.ValueOf(o.NodeNatDestinationRuleTranSLAtionOptions).IsZero() {
		subJSONStr, err := json.Marshal(o.NodeNatDestinationRuleTranSLAtionOptions)
		if err != nil {
			return nil, err
		}

		subData := make(map[string]interface{})
		err = json.Unmarshal(subJSONStr, &subData)
		if err != nil {
			return nil, err
		}
		jsonData["options"] = subData
	}

	// Return compiled data
	ret, err := json.Marshal(jsonData)
	if err != nil {
		return nil, err
	}
	return ret, nil
}

// UnmarshalJSON unmarshals json byte array into this object
func (o *NatDestinationRuleTranSLAtion) UnmarshalJSON(jsonStr []byte) error {
	jsonData := make(map[string]interface{})
	err := json.Unmarshal(jsonStr, &jsonData)
	if err != nil {
		return err
	}

	// Leafs

	if value, ok := jsonData["address"]; ok {
		o.LeafNatDestinationRuleTranSLAtionAddress = basetypes.NewStringValue(value.(string))
	} else {
		o.LeafNatDestinationRuleTranSLAtionAddress = basetypes.NewStringNull()
	}

	if value, ok := jsonData["port"]; ok {
		o.LeafNatDestinationRuleTranSLAtionPort = basetypes.NewStringValue(value.(string))
	} else {
		o.LeafNatDestinationRuleTranSLAtionPort = basetypes.NewStringNull()
	}

	// Tags

	// Nodes
	if value, ok := jsonData["options"]; ok {
		subJSONStr, err := json.Marshal(value)
		if err != nil {
			return err
		}

		o.NodeNatDestinationRuleTranSLAtionOptions = &NatDestinationRuleTranSLAtionOptions{}

		err = json.Unmarshal(subJSONStr, o.NodeNatDestinationRuleTranSLAtionOptions)
		if err != nil {
			return err
		}
	}

	return nil
}
