
terraform import vyos_protocols_static_multicast_interface_route_next_hop_interface.example "protocols__static__multicast__interface_route__<interface-route>__next_hop_interface__<next-hop-interface>"
