// Package resourcemodel code generated by /workspaces/terraform-provider-vyos/tools/build-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/thomasfinstad/terraform-provider-vyos/internal/terraform/customtypes"
)

// VpnIPsecSiteToSitePeerAuthentication describes the resource data model.
type VpnIPsecSiteToSitePeerAuthentication struct {
	// LeafNodes
	VpnIPsecSiteToSitePeerAuthenticationLocalID            customtypes.CustomStringValue `tfsdk:"local_id" json:"local-id,omitempty"`
	VpnIPsecSiteToSitePeerAuthenticationMode               customtypes.CustomStringValue `tfsdk:"mode" json:"mode,omitempty"`
	VpnIPsecSiteToSitePeerAuthenticationRemoteID           customtypes.CustomStringValue `tfsdk:"remote_id" json:"remote-id,omitempty"`
	VpnIPsecSiteToSitePeerAuthenticationUseXfivezeronineID customtypes.CustomStringValue `tfsdk:"use_x509_id" json:"use-x509-id,omitempty"`

	// TagNodes

	// Nodes
	VpnIPsecSiteToSitePeerAuthenticationRsa           types.Object `tfsdk:"rsa" json:"rsa,omitempty"`
	VpnIPsecSiteToSitePeerAuthenticationXfivezeronine types.Object `tfsdk:"x509" json:"x509,omitempty"`
}

// ResourceAttributes generates the attributes for the resource at this level
func (o VpnIPsecSiteToSitePeerAuthentication) ResourceAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		// LeafNodes

		"local_id": schema.StringAttribute{
			CustomType: customtypes.CustomStringType{},
			Optional:   true,
			MarkdownDescription: `Local ID for peer authentication

|  Format  |  Description  |
|----------|---------------|
|  txt  |  Local ID used for peer authentication  |
`,
		},

		"mode": schema.StringAttribute{
			CustomType: customtypes.CustomStringType{},
			Optional:   true,
			MarkdownDescription: `Authentication mode

|  Format  |  Description  |
|----------|---------------|
|  pre-shared-secret  |  Use pre-shared secret key  |
|  rsa  |  Use RSA key  |
|  x509  |  Use x.509 certificate  |
`,
		},

		"remote_id": schema.StringAttribute{
			CustomType: customtypes.CustomStringType{},
			Optional:   true,
			MarkdownDescription: `ID for remote authentication

|  Format  |  Description  |
|----------|---------------|
|  txt  |  ID used for peer authentication  |
`,

			// Default:          stringdefault.StaticString(`%any`),
			Computed: true,
		},

		"use_x509_id": schema.StringAttribute{
			CustomType: customtypes.CustomStringType{},
			Optional:   true,
			MarkdownDescription: `Use certificate common name as ID

`,
		},

		// TagNodes

		// Nodes

		"rsa": schema.SingleNestedAttribute{
			Attributes: VpnIPsecSiteToSitePeerAuthenticationRsa{}.ResourceAttributes(),
			Optional:   true,
			MarkdownDescription: `RSA keys

`,
		},

		"x509": schema.SingleNestedAttribute{
			Attributes: VpnIPsecSiteToSitePeerAuthenticationXfivezeronine{}.ResourceAttributes(),
			Optional:   true,
			MarkdownDescription: `X.509 certificate

`,
		},
	}
}
