
terraform import vyos_vpn_ipsec_remote_access_connection_authentication_local_users_username.example "vpn__ipsec__remote_access__connection__<connection>__authentication__local_users__username__<username>"
