// Package resourcemodel code generated by /workspaces/terraform-provider-vyos/tools/build-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

import (
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// ProtocolsBgpNeighborAddressFamilyIPvsixUnicastDisableSendCommunity describes the resource data model.
type ProtocolsBgpNeighborAddressFamilyIPvsixUnicastDisableSendCommunity struct {
	// LeafNodes
	LeafProtocolsBgpNeighborAddressFamilyIPvsixUnicastDisableSendCommunityExtended types.String `tfsdk:"extended" vyos:"extended,omitempty"`
	LeafProtocolsBgpNeighborAddressFamilyIPvsixUnicastDisableSendCommunityStandard types.String `tfsdk:"standard" vyos:"standard,omitempty"`

	// TagNodes (Bools that show if child resources have been configured)

	// Nodes
}

// ResourceSchemaAttributes generates the schema attributes for the resource at this level
func (o ProtocolsBgpNeighborAddressFamilyIPvsixUnicastDisableSendCommunity) ResourceSchemaAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		// LeafNodes

		"extended": schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Disable sending extended community attributes to this peer

`,
		},

		"standard": schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Disable sending standard community attributes to this peer

`,
		},

		// Nodes

	}
}

// MarshalJSON returns json encoded string as bytes or error if marshalling did not go well
func (o *ProtocolsBgpNeighborAddressFamilyIPvsixUnicastDisableSendCommunity) MarshalJSON() ([]byte, error) {
	jsonData := make(map[string]interface{})

	// Leafs

	if !o.LeafProtocolsBgpNeighborAddressFamilyIPvsixUnicastDisableSendCommunityExtended.IsNull() && !o.LeafProtocolsBgpNeighborAddressFamilyIPvsixUnicastDisableSendCommunityExtended.IsUnknown() {
		jsonData["extended"] = o.LeafProtocolsBgpNeighborAddressFamilyIPvsixUnicastDisableSendCommunityExtended.ValueString()
	}

	if !o.LeafProtocolsBgpNeighborAddressFamilyIPvsixUnicastDisableSendCommunityStandard.IsNull() && !o.LeafProtocolsBgpNeighborAddressFamilyIPvsixUnicastDisableSendCommunityStandard.IsUnknown() {
		jsonData["standard"] = o.LeafProtocolsBgpNeighborAddressFamilyIPvsixUnicastDisableSendCommunityStandard.ValueString()
	}

	// Nodes

	// Return compiled data
	ret, err := json.Marshal(jsonData)
	if err != nil {
		return nil, err
	}
	return ret, nil
}

// UnmarshalJSON unmarshals json byte array into this object
func (o *ProtocolsBgpNeighborAddressFamilyIPvsixUnicastDisableSendCommunity) UnmarshalJSON(jsonStr []byte) error {
	jsonData := make(map[string]interface{})
	err := json.Unmarshal(jsonStr, &jsonData)
	if err != nil {
		return err
	}

	// Leafs

	if value, ok := jsonData["extended"]; ok {
		o.LeafProtocolsBgpNeighborAddressFamilyIPvsixUnicastDisableSendCommunityExtended = basetypes.NewStringValue(value.(string))
	} else {
		o.LeafProtocolsBgpNeighborAddressFamilyIPvsixUnicastDisableSendCommunityExtended = basetypes.NewStringNull()
	}

	if value, ok := jsonData["standard"]; ok {
		o.LeafProtocolsBgpNeighborAddressFamilyIPvsixUnicastDisableSendCommunityStandard = basetypes.NewStringValue(value.(string))
	} else {
		o.LeafProtocolsBgpNeighborAddressFamilyIPvsixUnicastDisableSendCommunityStandard = basetypes.NewStringNull()
	}

	// Nodes

	return nil
}
