
terraform import vyos_interfaces_pseudo_ethernet_vif_s_dhcpv6_options_pd_interface.example "interfaces__pseudo_ethernet__<pseudo-ethernet>__vif_s__<vif-s>__dhcpv6_options__pd__<pd>__interface__<interface>"
