
terraform import vyos_vrf_name_protocols_isis_fast_reroute_lfa_local_tiebreaker_downstream_index.example "vrf__name__<name>__protocols__isis__fast_reroute__lfa__local__tiebreaker__downstream__index__<index>"
