
terraform import vyos_service_dhcpv6_server_shared_network_name_subnet_prefix_delegation_prefix.example "service__dhcpv6_server__shared_network_name__<shared-network-name>__subnet__<subnet>__prefix_delegation__prefix__<prefix>"
