// Package resourcemodel code generated by /workspaces/terraform-provider-vyos/tools/build-terraform-resource-full/main.go. DO NOT EDIT.
package resourcemodel

import (
	"encoding/json"
	"reflect"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// InterfacesLoopback describes the resource data model.
type InterfacesLoopback struct {
	ID types.String `tfsdk:"identifier" vyos:",self-id"`

	// LeafNodes
	LeafInterfacesLoopbackAddress     types.String `tfsdk:"address" vyos:"address,omitempty"`
	LeafInterfacesLoopbackDescrIPtion types.String `tfsdk:"description" vyos:"description,omitempty"`
	LeafInterfacesLoopbackRedirect    types.String `tfsdk:"redirect" vyos:"redirect,omitempty"`

	// TagNodes (Bools that show if child resources have been configured)

	// Nodes
	NodeInterfacesLoopbackIP     *InterfacesLoopbackIP     `tfsdk:"ip" vyos:"ip,omitempty"`
	NodeInterfacesLoopbackMirror *InterfacesLoopbackMirror `tfsdk:"mirror" vyos:"mirror,omitempty"`
}

// GetVyosPath returns the list of strings to use to get to the correct vyos configuration
func (o *InterfacesLoopback) GetVyosPath() []string {
	return []string{
		"interfaces",
		"loopback",
		o.ID.ValueString(),
	}
}

// ResourceSchemaAttributes generates the schema attributes for the resource at this level
func (o InterfacesLoopback) ResourceSchemaAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"identifier": schema.StringAttribute{
			Required: true,
			MarkdownDescription: `Loopback Interface

    |  Format  |  Description  |
    |----------|---------------|
    |  lo  |  Loopback interface  |

`,
		},

		// LeafNodes

		"address": schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `IP address

    |  Format  |  Description  |
    |----------|---------------|
    |  ipv4net  |  IPv4 address and prefix length  |
    |  ipv6net  |  IPv6 address and prefix length  |

`,
		},

		"description": schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Description

    |  Format  |  Description  |
    |----------|---------------|
    |  txt  |  Description  |

`,
		},

		"redirect": schema.StringAttribute{
			Optional: true,
			MarkdownDescription: `Redirect incoming packet to destination

    |  Format  |  Description  |
    |----------|---------------|
    |  txt  |  Destination interface name  |

`,
		},

		// Nodes

		"ip": schema.SingleNestedAttribute{
			Attributes: InterfacesLoopbackIP{}.ResourceSchemaAttributes(),
			Optional:   true,
			MarkdownDescription: `IPv4 routing parameters

`,
		},

		"mirror": schema.SingleNestedAttribute{
			Attributes: InterfacesLoopbackMirror{}.ResourceSchemaAttributes(),
			Optional:   true,
			MarkdownDescription: `Mirror ingress/egress packets

`,
		},
	}
}

// MarshalJSON returns json encoded string as bytes or error if marshalling did not go well
func (o *InterfacesLoopback) MarshalJSON() ([]byte, error) {
	jsonData := make(map[string]interface{})

	// Leafs

	if !o.LeafInterfacesLoopbackAddress.IsNull() && !o.LeafInterfacesLoopbackAddress.IsUnknown() {
		jsonData["address"] = o.LeafInterfacesLoopbackAddress.ValueString()
	}

	if !o.LeafInterfacesLoopbackDescrIPtion.IsNull() && !o.LeafInterfacesLoopbackDescrIPtion.IsUnknown() {
		jsonData["description"] = o.LeafInterfacesLoopbackDescrIPtion.ValueString()
	}

	if !o.LeafInterfacesLoopbackRedirect.IsNull() && !o.LeafInterfacesLoopbackRedirect.IsUnknown() {
		jsonData["redirect"] = o.LeafInterfacesLoopbackRedirect.ValueString()
	}

	// Nodes

	if !reflect.ValueOf(o.NodeInterfacesLoopbackIP).IsZero() {
		subJSONStr, err := json.Marshal(o.NodeInterfacesLoopbackIP)
		if err != nil {
			return nil, err
		}

		subData := make(map[string]interface{})
		err = json.Unmarshal(subJSONStr, &subData)
		if err != nil {
			return nil, err
		}
		jsonData["ip"] = subData
	}

	if !reflect.ValueOf(o.NodeInterfacesLoopbackMirror).IsZero() {
		subJSONStr, err := json.Marshal(o.NodeInterfacesLoopbackMirror)
		if err != nil {
			return nil, err
		}

		subData := make(map[string]interface{})
		err = json.Unmarshal(subJSONStr, &subData)
		if err != nil {
			return nil, err
		}
		jsonData["mirror"] = subData
	}

	// Return compiled data
	ret, err := json.Marshal(jsonData)
	if err != nil {
		return nil, err
	}
	return ret, nil
}

// UnmarshalJSON unmarshals json byte array into this object
func (o *InterfacesLoopback) UnmarshalJSON(jsonStr []byte) error {
	jsonData := make(map[string]interface{})
	err := json.Unmarshal(jsonStr, &jsonData)
	if err != nil {
		return err
	}

	// Leafs

	if value, ok := jsonData["address"]; ok {
		o.LeafInterfacesLoopbackAddress = basetypes.NewStringValue(value.(string))
	} else {
		o.LeafInterfacesLoopbackAddress = basetypes.NewStringNull()
	}

	if value, ok := jsonData["description"]; ok {
		o.LeafInterfacesLoopbackDescrIPtion = basetypes.NewStringValue(value.(string))
	} else {
		o.LeafInterfacesLoopbackDescrIPtion = basetypes.NewStringNull()
	}

	if value, ok := jsonData["redirect"]; ok {
		o.LeafInterfacesLoopbackRedirect = basetypes.NewStringValue(value.(string))
	} else {
		o.LeafInterfacesLoopbackRedirect = basetypes.NewStringNull()
	}

	// Nodes
	if value, ok := jsonData["ip"]; ok {
		subJSONStr, err := json.Marshal(value)
		if err != nil {
			return err
		}

		o.NodeInterfacesLoopbackIP = &InterfacesLoopbackIP{}

		err = json.Unmarshal(subJSONStr, o.NodeInterfacesLoopbackIP)
		if err != nil {
			return err
		}
	}
	if value, ok := jsonData["mirror"]; ok {
		subJSONStr, err := json.Marshal(value)
		if err != nil {
			return err
		}

		o.NodeInterfacesLoopbackMirror = &InterfacesLoopbackMirror{}

		err = json.Unmarshal(subJSONStr, o.NodeInterfacesLoopbackMirror)
		if err != nil {
			return err
		}
	}

	return nil
}
