
terraform import vyos_service_dhcp_server_shared_network_name_subnet_range_option_static_route.example "service__dhcp-server__shared-network-name__<shared-network-name>__subnet__<subnet>__range__<range>__option__static-route__<static-route>"
