
terraform import vyos_service_dhcp_server_shared_network_name_subnet_range_option_static_route.example "service__dhcp_server__shared_network_name__<shared-network-name>__subnet__<subnet>__range__<range>__option__static_route__<static-route>"
